project:
  type: website
  output-dir: docs

website:
  title: "Aaron Powell"
  description: "Data Science Portfolio & Projects"
  site-url: https://powellonpoint.github.io
  repo-url: https://github.com/powellonpoint/powellonpoint.github.io
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: books.qmd
        text: Books
      - href: research.qmd
        text: Research
    right:
      - text: '<img src="images/icons/github.svg" style="height:24px; vertical-align: middle;">'
        href: https://github.com/powellonpoint
      - text: '<img src="images/icons/linkedin.svg" style="height:24px; vertical-align: middle;">'
        href: https://linkedin.com/in/aaronmpowell2
      - text: '<img src="images/icons/x-custom.svg" style="height:24px; vertical-align: middle;">'
        href: https://x.com/powellonpoint
      - text: '<img src="images/icons/cif--us.svg" style="height:22px; vertical-align: middle;">'
        href: army.html

format:
  html:
    theme: spacelab
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 150px
    code-copy: true
    code-overflow: wrap

bibliography: references.bib

execute:
  freeze: auto



